[tasks.run_front]
script = ["cd ./sysinfo-sse-frontend", "pnpm run dev"]

[tasks.install_front]
script = ["cd ./sysinfo-sse-frontend", "pnpm install"]

[tasks.run_back]
script = ["cd ./sysinfo-sse-backend", "cargo run"]

[tasks.dev]
run_task = { name = ["run_front", "run_back"], parallel = true }
